# Generated by Django 3.2.16 on 2023-10-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='description',
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='currency',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='currency',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
